Repository treee111/wahooMapsCreator, pull requests merged in 2023-11, with the labels that each got.

#223 [FIX] include elevation data only if requested by the user, i.e. if `-con` is given
  wahoomc/main.py
  wahoomc/osm_maps_functions.py
Labels: bug

#222 [DEV] Fix unittests
  docs/CONTRIBUTING.md
  docs/COPY_TO_WAHOO.md
  docs/pictures/unittest-land-poligons.png
  tests/resources/macos/134/89.map
  tests/resources/macos/134/89.map.lzma
  tests/resources/macos/134/89/merged.osm.pbf
  tests/resources/macos/134/89/split-liechtenstein-names.osm.pbf
  tests/resources/macos/134/89/split-liechtenstein.osm.pbf
  tests/resources/macos/137/100.map
  tests/resources/macos/137/100.map.lzma
  tests/resources/macos/137/100/split-malta-names.osm.pbf
  tests/resources/macos/137/100/split-malta.osm.pbf
  tests/resources/macos/138/100.map
  tests/resources/macos/138/100.map.lzma
  tests/resources/macos/138/100/merged.osm.pbf
  tests/resources/macos/138/100/split-malta-names.osm.pbf
  tests/resources/macos/138/100/split-malta.osm.pbf
  tests/resources/macos/liechtenstein/filtered.o5m.pbf
  tests/resources/macos/malta/filtered.o5m.pbf
  tests/resources/windows/134/89.map
  tests/resources/windows/134/89.map.lzma
  tests/resources/windows/134/89/merged.osm.pbf
  tests/resources/windows/134/89/split-liechtenstein-names.osm.pbf
  tests/resources/windows/134/89/split-liechtenstein.osm.pbf
  tests/resources/windows/137/100.map
  tests/resources/windows/137/100.map.lzma
  tests/resources/windows/137/100.map.lzma.17
  tests/resources/windows/137/100/land.prj
  tests/resources/windows/137/100/land.shp
  tests/resources/windows/137/100/land.shx
  tests/resources/windows/137/100/land1.osm
  tests/resources/windows/137/100/merged.osm.pbf
  tests/resources/windows/137/100/sea.osm
  tests/resources/windows/137/100/split-malta-names.osm.pbf
  tests/resources/windows/137/100/split-malta.osm.pbf
  tests/resources/windows/138/100.map
  tests/resources/windows/138/100.map.lzma
  tests/resources/windows/138/100/merged.osm.pbf
  tests/resources/windows/138/100/split-malta-names.osm.pbf
  tests/resources/windows/138/100/split-malta.osm.pbf
  tests/resources/windows/liechtenstein/filtered.o5m
  tests/resources/windows/malta/filtered.o5m
  tests/test_constants.py
Labels: infrastructure

#226 [DEV] remove deprecated linting settings
  .vscode/settings.json
Labels: infrastructure

#225 [FEAT] Add logging of timing for total time, each main section and for each tile generation step
  wahoomc/downloader.py
  wahoomc/main.py
  wahoomc/osm_maps_functions.py
  wahoomc/timings.py
Labels: enhancement

#232 [FEAT] Use proper tool name in error message, reference Osmium or osmconvert
  wahoomc/osm_maps_functions.py
Labels: refactoring

#233 [DEV] move OsmData classes from osm_maps_functions.py to osm_data.py
  tests/test_osm_maps.py
  wahoomc/main.py
  wahoomc/osm_data.py
  wahoomc/osm_maps_functions.py
Labels: refactoring
